Messages:
# Вывод сообщения тем кого нет в списке Players
# Print the message to those who are not in the list of Players
  not_on_the_list: '&9* &dAConsole &9* &7Вас нет в списке для использывания консоли'
# Вывод сообщения если эта команда не в списке разрешённых
# Print the message if this command is not in the allowed list
  white-message: '&9* &dAConsole &9* &7Эта команда не входит в список разрешённых' 
# Вывод сообщения при вводе /console
# Display message when you enter /console
  Command: 
  - '&9|'
  - '&9| &dAConsole &9| &fВкл/выкл режим слежки - &d/console spy'
  - '&9| &dAConsole &9| &fПерезагрузить конфиг - &d/console reload'
  - '&9| &dAConsole &9| &fВкл/выкл консоль - &d/console toggle'
  - '&9| &dAConsole &9| &fНаписать в консоль - &d/console [Ваша_Команда]'
  - '&9|'
# Вывод сообщения если пытались использовать команду от другого игрока
  sudo: '&9* &dAConsole &9* &7Вы не можете использовать эту команду от другого игрока'
# Вывод сообщения если команда прошла успешно
# Print the message if the command was successful
  Complete: '&9* &dAConsole &9* &7Команда успешно выполнена'
# Вывод сообщения если кто то ввёл отключенную команду
# Print the message if someone entered a disabled team
  blacklist-message: '&9* &dAConsole &9* &7Данная команда отключена в конфиге'
# Вывод сообщения при вводе /console reload
# Message when you type /console reload
  reload: '&9* &dAConsole &9* &7Плагин успешно перезагружен'
# Вывод сообщения если у игрока нет оп
  no_op: '&9* &dAConsole &9* &7У вас нет оп для использывания данной команды'
# Вывод сообщение если консоль включили
  enabled: '&9* &dAConsole &9* &7Консоль &aвключена'
# Вывод сообщение если консоль отключили
  disabled: '&9* &dAConsole &9* &7Консоль &cвыключена'
# Вывод сообщения при включении,выключении и получении получении информации
  Spy:
# Вывод сообщения если слежка включена(при переключении /console spy)
    enable: '&9* &dAConsole &9* &7Слежка &aвключена'
# Вывод сообщения если слежка выключена(при переключении /console spy)
    disable: '&9* &dAConsole &9* &7Слежка &cвыключена'
# Вывод сообщения если слежка включена 
# @command - Команда которую ввёл игрок 
# @player - игрок который ввёл команду 
# @prefix - префикс игрока
# @cancel - выполнилась или не вполнилась команда
    message: '&9* &dAConsole &9* &d@player &6использовал(а) команду - &c@command'

# Лог
Log:
# Записывать всё в лог команды, сообщения и т.д
  global: false
# Создать ли лог файл если true - да | false - нет
  enabled: true
# Формат в котором сохронять
  save: '%date% %name% использовал(а): /%command%'
# Удалять файл при выключении сервера
  delete: false
  
ignore:
# Команды которые не будут выводиться в ConsoleSpy
  commands:
  - 'l'
  - 'login'
  - 'reg'
  - 'mail'
  - 'register'
  - 'changepassword'
  - 'email'
  # Каких игроков не будет видно в ConsoleSpy
  admins:
  - 'CrticaMobs'

# Будет ли работать чёрный список true - да | false - нет
# Will it work blacklist true - Yes | false - no
black-list: false
# Список команд которые не будут работать
# List of commands which will not work
blacklist:
- 'op'
- 'deop'
- 'ban'
- 'mute'

# Будет ли команда работать только для опнутых
OpPlayers: false

# Будет ли работать белый список true - да | false - нет
# Will it work the white list true - Yes | false - no
white-list: false
# Список команд которые будут работать
# A list of commands that will work
whitelist:
- 'heal'
- 'spawn'
- 'clear'

# Будет ли работать список игроков которым доступна консоль
# Will it work the list of players allowed access to the console
Allow-Players: false
# Список игроков которым доступна мини-консоль
# The list of players which is available mini-console
Players:
- 'CriticaMobs'

Permissions:
# Права на команду /console | по умолчанию true
# Rights to team /console | default true
  command:
    enabled: true
    permission: 'console.console'
# Вывод сообщения если не хватает прав
# Print the message if not enough rights
    message: '&9| &dAConsole &9| &cУ вас нет прав на использование этой команды'
  spy:
    enabled: true
    permission: 'console.spy'
# Вывод сообщения если не хватает прав
# Print the message if not enough rights
    message: '&9| &dAConsole &9| &cУ вас нет прав что бы следить за игроками'
  reload:
    enabled: true
    permission: 'console.relopad'
# Вывод сообщения если не хватает прав
# Print the message if not enough rights
    message: '&9| &dAConsole &9| &cУ вас нет прав что бы перезагрузить конфиг'
  toggle:
    enabled: true
    permission: 'console.toggle'
# Вывод сообщения если не хватает прав
# Print the message if not enough rights
    message: '&9| &dAConsole &9| &cУ вас нет прав что бы отключить консоль'